[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts =
    --cov=apps
    --cov-report=html
    --cov-report=term-missing
    --tb=short
    -v
testpaths = .
norecursedirs = .git .tox dist build *.egg __pycache__
